name: Oli cat

on:
  push:
    paths-ignore: 
      - 'Release/**'

env:
  ACTION_MAIL: "o.gruetzmann@gmail.com"
  ACTION_NAME: "ogruetzmann"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cat
      run: cat $GITHUB_WORKSPACE/* >> Release/GRPluginStands.txt
    - name: ls
      run: ls -al $GITHUB_WORKSPACE
    - name: push
      uses: ludeeus/action-push@0.0.1
